# Generated by Django 2.1.2 on 2018-11-03 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='outstanding_balance',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='payment_late',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='payment_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_guest',
            field=models.BooleanField(default=True),
        ),
    ]
